paragraph component font style option and additional colors
goranalkovic-infinum/starter-task pull request #19
Opened 2021-01-21 09:07 UTC by goranalkovic-infinum

2021-01-21 09:13 UTC, iruzevic requested changes

2021-01-21 09:13 UTC, iruzevic commented on src/Blocks/components/paragraph/manifest.json
> +				"label": "Excerptional (16px)",
as in the previous PR

2021-01-21 09:13 UTC, iruzevic commented on src/Blocks/components/paragraph/manifest.json
> +				"label": "Datey (14px)",
🆙

2021-01-21 09:13 UTC, iruzevic commented on src/Blocks/components/paragraph/paragraph-style.scss
> +			excerptional: (
:up

2021-01-21 09:13 UTC, iruzevic commented on src/Blocks/components/paragraph/paragraph-style.scss
> +			datey: (
🆙

2021-01-21 09:13 UTC, iruzevic commented on src/Blocks/components/paragraph/paragraph-style.scss
> +			excerptional: (
:up

2021-01-21 09:13 UTC, iruzevic commented on src/Blocks/components/paragraph/paragraph-style.scss
> +			datey: (
🆙

2021-01-21 09:13 UTC, iruzevic commented on src/Blocks/components/paragraph/paragraph-style.scss
> +	&__fontStyle--italic {
we dont use camelCase on selectors.

&__font-style--italic

2021-01-21 09:13 UTC, iruzevic commented on src/Blocks/components/paragraph/components/paragraph-editor.js
> +		selector(paragraphFontStyle, componentClass, 'fontStyle', paragraphFontStyle),
we dont use camelCase on selectors.

2021-01-21 09:13 UTC, iruzevic commented on src/Blocks/components/paragraph/paragraph.php
> +	Components::selector($paragraphFontStyle, $componentClass, 'fontStyle', $paragraphFontStyle),
we dont use camelCase on selectors.

2021-01-21 10:31 UTC, dingo-d commented on src/Blocks/components/paragraph/manifest.json
> +				"label": "Excerptional (16px)",
Not sure we need descriptive names for font sizes 😂 

There is a list of font sizes on the net, and it's usually something like small, tiny, medium, default, large, etc. (plus comparatives larger, largest...). This gives us enough range 😄

2021-01-21 10:31 UTC, dingo-d approved these changes

2021-01-22 11:10 UTC, iruzevic requested changes

2021-01-22 11:10 UTC, iruzevic commented on src/Blocks/components/paragraph/paragraph-style.scss
> +		muted: $base-text-muted-color
all colors must go to the global colors manifest. If we define some in manifest and some in code it will become a mess very fast.

2021-01-22 12:29 UTC, iruzevic commented
I have left you some comments to fix. Please ask for rereview after you have fixed everything.

2021-01-25 08:47 UTC, iruzevic approved these changes

2021-01-26 09:46 UTC, merged